export const PLAYER_MOVEMENT_SPEED = 4;
export const LIGHT_OF_BLESSINGS_DURATION = 5000;
export const LANTERN_BRIGHTNESS_RADIUS = 250;
export const LANTERN_BRIGHTNESS_DECREASE_RATE = 1;
export const LANTERN_FOG_MAX_INNER_RADIUS = 520;
export const LANTERN_FOG_MAX_OUTER_RADIUS = 900;
